## 프로젝트 이름
spring.application.name=ch12-stdio-mcp-server-filesystem

## MCP Server 구성
spring.ai.mcp.server.name=ch12-stdio-mcp-server-filesystem
spring.ai.mcp.server.version="0.0.1-SNAPSHOT"
# MCP Server 프로토콜 구성
spring.ai.mcp.server.stdio=true
# 독립 실행형
spring.main.web-application-type=none
# 배너 출력 금지
spring.main.banner-mode=off
# MCP Server API 동기/비동기식 구성
spring.ai.mcp.server.type=SYNC