## 프로젝트 이름
spring.application.name=appendix-chat-model-api-ollama

## 서버 포트
server.port=8080

## 터미널 칼라 출력
spring.output.ansi.enabled=ALWAYS

## 로깅
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n

## 파일 업로드
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

## 정적 리소스에 대해 캐시 사용 안 함
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

## Ollama
spring.ai.ollama.base-url=http://localhost:11434

# llama 3.1 모델
# spring.ai.ollama.chat.model=llama3.1:8b

# qwen 3.5는 추론 모델
# Ollama에서는 기본적으로 think 모드를 활성화시킴
# 추론으로 최대 토큰 수를 초과하면 답변이 잘릴 수 있음
# 추론으로 인해 발생하는 비용을 줄이기 위해 think 모드를 비활성화함
spring.ai.ollama.chat.model=qwen3.5:9b
spring.ai.ollama.chat.think=false

