## 프로젝트 이름
spring.application.name=ch12-webflux-mcp-server

## 서버 포트 구성
server.port=8081

## 터미널 컬러 출력 구성
spring.output.ansi.enabled=ALWAYS

## 로깅
logging.pattern.console=%clr(%-5level){green} %clr(%logger.%M\\(\\)){cyan}: %msg%n

## MCP Server 구성
spring.ai.mcp.server.name=ch12-webflux-mcp-server
spring.ai.mcp.server.version=0.0.1-SNAPSHOT
# MCP Server 프로토콜 구성
spring.ai.mcp.server.protocol=STREAMABLE
# MCP Server API 동기/비동기식 구성
spring.ai.mcp.server.type=ASYNC

## SerpApi
serpapi.api-key=${SERPAPI_API_KEY}