## 프로젝트 이름
spring.application.name=ch11-tool-calling

## 서버 포트
server.port=8080

## 터미널 칼라 출력
spring.output.ansi.enabled=ALWAYS

## 로깅
logging.pattern.console=%clr(%-5level){green} %clr(%logger.%M\\(\\)){cyan}: %msg%n
logging.level.org.springframework.ai.tool=DEBUG
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

## 파일 업로드
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

## 정적 리소스에 대해 캐시 사용 안 함
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

## OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}

# 애플리케이션에서 예외 처리
# spring.ai.tools.throw-exception-on-error=true

## PostgreSQL 연결
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

## 기본 vector_store 테이블 생성
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.openai.embedding.model=text-embedding-3-large
spring.ai.vectorstore.pgvector.dimensions=3072
spring.ai.vectorstore.pgvector.index-type=none 
# 인텍스 수동 생성해야함 (other/sql/ch10-text-embedding-3-large_vector.sql 참조)

## 도구 검색 기능을 위한 설정

# 기본 Tool Calling 실습
spring.ai.chat.client.tool-search-advisor.enabled=true

# 아래 설정은 false 상태에서는 사실상 사용되지 않음
spring.ai.chat.client.tool-search-advisor.tool-index-type=regex
spring.ai.chat.client.tool-search-advisor.session-id-key-name=tool-search-id
spring.ai.chat.client.tool-search-advisor.max-results=5

## SerpApi
serpapi.api-key=${SERPAPI_API_KEY}


